from __future__ import annotations

import argparse
from types import ModuleType


def register_agent(sub: argparse._SubParsersAction, handlers: ModuleType) -> None:
    agent = sub.add_parser("agent")
    agent_sub = agent.add_subparsers(dest="agent_command", required=True)
    agent_install = agent_sub.add_parser("install")
    agent_install.add_argument("--project", required=True)
    agent_install.add_argument("--target", choices=["codex", "claude-code", "all"], required=True)
    agent_install.set_defaults(func=handlers.cmd_agent_install)


def register_instruct(sub: argparse._SubParsersAction, handlers: ModuleType) -> None:
    instruct = sub.add_parser("instruct")
    instruct.add_argument("--task", required=True)
    instruct.set_defaults(func=handlers.cmd_instruct)


def register_report(sub: argparse._SubParsersAction, handlers: ModuleType) -> None:
    report = sub.add_parser("report")
    report.add_argument("--task")
    report.add_argument("--project", help="Project id. Defaults to the current directory name.")
    report.add_argument("--file")
    report.add_argument("--agent", default="unknown")
    report.set_defaults(func=handlers.cmd_facade_report)
    report_sub = report.add_subparsers(dest="report_command")
    report_import = report_sub.add_parser("import")
    report_import.add_argument("--task", required=True)
    report_import.add_argument("--file")
    report_import.add_argument("--agent", default="unknown")
    report_import.set_defaults(func=handlers.cmd_report_import)


def register_understanding(sub: argparse._SubParsersAction, handlers: ModuleType) -> None:
    understanding = sub.add_parser("understanding")
    understanding_sub = understanding.add_subparsers(dest="understanding_command", required=True)
    understanding_prepare = understanding_sub.add_parser("prepare")
    understanding_prepare.add_argument("--task", required=True)
    understanding_prepare.set_defaults(func=handlers.cmd_understanding_prepare)
    understanding_import = understanding_sub.add_parser("import")
    understanding_import.add_argument("--task", required=True)
    understanding_import.add_argument("--file")
    understanding_import.set_defaults(func=handlers.cmd_understanding_import)
    understanding_approve = understanding_sub.add_parser("approve")
    understanding_approve.add_argument("--task", required=True)
    understanding_approve.add_argument("--actor", choices=["human", "ai"], required=True)
    understanding_approve.add_argument("--reason", required=True)
    understanding_approve.add_argument("--human-confirm", action="store_true")
    understanding_approve.add_argument("--decision-note", default="")
    understanding_approve.set_defaults(func=handlers.cmd_understanding_approve)


def register_outcome(sub: argparse._SubParsersAction, handlers: ModuleType) -> None:
    outcome = sub.add_parser("outcome")
    outcome_sub = outcome.add_subparsers(dest="outcome_command", required=True)
    for command, decision in [
        ("accept", "accepted"),
        ("reject", "rejected"),
        ("accept-with-concerns", "accepted_with_concerns"),
        ("partial-accept", "partial_accept"),
        ("rework-required", "rework_required"),
    ]:
        outcome_parser = outcome_sub.add_parser(command)
        outcome_parser.add_argument("--task", required=True)
        outcome_parser.add_argument("--reason", required=True)
        outcome_parser.add_argument("--concern", action="append", default=[])
        if decision in ("accepted", "accepted_with_concerns"):
            outcome_parser.add_argument("--human-confirm", action="store_true", help="Required after a human completion decision.")
            outcome_parser.add_argument("--decision-note", required=True, help="Human-written acceptance note. AI workers must not invent this.")
        outcome_parser.set_defaults(func=handlers.cmd_outcome_record, decision=decision)


def register_review(sub: argparse._SubParsersAction, handlers: ModuleType) -> None:
    review = sub.add_parser("review")
    review_sub = review.add_subparsers(dest="review_command", required=True)
    review_request = review_sub.add_parser("request")
    review_request.add_argument("--task", required=True)
    review_request.add_argument("--from", dest="requester", required=True)
    review_request.add_argument("--to", dest="reviewer", required=True)
    review_request.add_argument("--reason", required=True)
    review_request.add_argument("--wait", action="store_true")
    review_request.add_argument("--wait-timeout", type=float, default=600.0)
    review_request.add_argument("--poll-interval", type=float, default=1.0)
    review_request.set_defaults(func=handlers.cmd_review_request)
    review_dispatch = review_sub.add_parser("dispatch", help="Run a local CLI reviewer process fallback; prefer MCP dispatch_review for normal AI review handoff.")
    review_dispatch.add_argument("--task")
    review_dispatch.add_argument("--project")
    review_dispatch.add_argument("--actor", required=True)
    review_dispatch.add_argument("--reviewer", required=True)
    review_dispatch.add_argument("--reason", default="dispatched agent review")
    review_dispatch.add_argument("--auto-start", dest="auto_start", action="store_true", default=None)
    review_dispatch.add_argument("--no-auto-start", dest="auto_start", action="store_false")
    review_dispatch.add_argument("--auto-configure", dest="auto_configure", action="store_true", default=True)
    review_dispatch.add_argument("--no-auto-configure", dest="auto_configure", action="store_false")
    review_dispatch.add_argument("--config", help="Reviewer TOML config path. Defaults to .nilo/reviewers.toml. This is for local CLI reviewer process fallback.")
    review_dispatch.set_defaults(func=handlers.cmd_review_dispatch)
    review_quick = review_sub.add_parser("quick", help="Run a local CLI reviewer process diagnostic/fallback; not the normal AI review handoff.")
    review_quick.add_argument("--task")
    review_quick.add_argument("--project")
    review_quick.add_argument("--actor", default="codex")
    review_quick.add_argument("--reviewer", required=True)
    review_quick.add_argument("--reason", default="quick agent review")
    review_quick_import = review_quick.add_mutually_exclusive_group()
    review_quick_import.add_argument("--import", dest="should_import", action="store_true", default=True)
    review_quick_import.add_argument("--no-import", dest="should_import", action="store_false")
    review_quick.add_argument("--timeout", type=float, default=120.0)
    review_quick.add_argument("--auto-configure", dest="auto_configure", action="store_true", default=True)
    review_quick.add_argument("--no-auto-configure", dest="auto_configure", action="store_false")
    review_quick.add_argument("--config", help="Reviewer TOML config path. Defaults to .nilo/reviewers.toml. This is for local CLI fallback / diagnostics only.")
    review_quick.set_defaults(func=handlers.cmd_review_quick)
    review_init = review_sub.add_parser("init")
    review_init.add_argument("--reviewer", action="append", default=[])
    review_init.add_argument("--config", help="Reviewer TOML config path. Defaults to .nilo/reviewers.toml")
    review_init.add_argument("--overwrite", action="store_true")
    review_init.set_defaults(func=handlers.cmd_review_init)
    review_doctor = review_sub.add_parser("doctor")
    review_doctor.add_argument("--reviewer", action="append", default=[])
    review_doctor.add_argument("--config", help="Reviewer TOML config path. Defaults to .nilo/reviewers.toml")
    review_doctor.set_defaults(func=handlers.cmd_review_doctor)
    review_delegate = review_sub.add_parser("delegate")
    review_delegate.add_argument("--project", required=True)
    review_delegate.add_argument("--task")
    review_delegate.add_argument("--from", dest="requester", default="codex")
    review_delegate.add_argument("--to", dest="reviewer", default="claude-code")
    review_delegate.add_argument("--reason", default="delegated review")
    review_delegate.add_argument("--write-default", action="store_true")
    review_delegate.add_argument("--wait", action="store_true")
    review_delegate.add_argument("--wait-timeout", type=float, default=600.0)
    review_delegate.add_argument("--poll-interval", type=float, default=1.0)
    review_delegate.set_defaults(func=handlers.cmd_review_delegate)
    review_claude = review_sub.add_parser("human-launch-claude", help="Human-requested Claude CLI launch helper; normal AI review handoff should use MCP dispatch_review.")
    review_claude.add_argument("--project", required=True)
    review_claude.add_argument("--task")
    review_claude.add_argument("--from", dest="requester", default="codex")
    review_claude.add_argument("--reason", default="ユーザー依頼によるレビュー")
    review_claude.add_argument("--mcp-config", default=".mcp.json")
    review_claude.add_argument("--permission-mode", default="bypassPermissions")
    review_claude.add_argument("--timeout", type=float, default=600.0)
    review_claude.add_argument("--write-default", action="store_true")
    review_claude.add_argument("--dry-run", action="store_true")
    review_claude.add_argument("--verbose", action="store_true")
    review_claude.set_defaults(func=handlers.cmd_review_human_launch_claude)
    review_prepare = review_sub.add_parser("prepare")
    review_prepare.add_argument("--task")
    review_prepare.add_argument("--project")
    review_prepare.add_argument("--reviewer")
    review_prepare.add_argument("--review")
    review_prepare_output = review_prepare.add_mutually_exclusive_group()
    review_prepare_output.add_argument("--file")
    review_prepare_output.add_argument("--write-default", action="store_true")
    review_prepare.set_defaults(func=handlers.cmd_review_prepare)
    review_template = review_sub.add_parser("template")
    review_template.add_argument("--review", required=True)
    review_template_output = review_template.add_mutually_exclusive_group(required=True)
    review_template_output.add_argument("--file")
    review_template_output.add_argument("--write-default", action="store_true")
    review_template.set_defaults(func=handlers.cmd_review_template)
    review_import = review_sub.add_parser("import")
    review_import.add_argument("--task", required=True)
    review_import.add_argument("--review")
    review_import.add_argument("--file")
    review_import.add_argument("--required-score", action="append", default=[])
    review_import.add_argument("--strict-scores", action="store_true")
    review_import.add_argument("--allow-unknown-scores", action="store_true")
    review_import.add_argument("--reviewer")
    review_import.add_argument("--last-seen-event-id", default="")
    review_import.add_argument("--context-token", default="")
    review_import.set_defaults(func=handlers.cmd_review_import)
    review_status = review_sub.add_parser("status")
    review_status.add_argument("--task", required=True)
    review_status.add_argument("--format", choices=["text", "json"], default="text")
    review_status.set_defaults(func=handlers.cmd_review_status)
    review_show = review_sub.add_parser("show")
    review_show.add_argument("--task", required=True)
    review_show.add_argument("--ai", action="store_true", default=True)
    review_show.add_argument("--format", choices=["text", "json"], default="text")
    review_show.set_defaults(func=handlers.cmd_review_show)
    review_withdraw = review_sub.add_parser("withdraw")
    review_withdraw.add_argument("--review", required=True)
    review_withdraw.add_argument("--reason", required=True)
    review_withdraw.add_argument("--actor", default="operator")
    review_withdraw.set_defaults(func=handlers.cmd_review_withdraw)
    review_wait = review_sub.add_parser("wait")
    review_wait.add_argument("--review", required=True)
    review_wait.add_argument("--timeout", type=float, default=600.0)
    review_wait.add_argument("--poll-interval", type=float, default=1.0)
    review_wait.add_argument("--actor", default="operator")
    review_wait.add_argument("--timeout-reason", default="review wait timed out")
    review_wait.set_defaults(func=handlers.cmd_review_wait)
    review_finding = review_sub.add_parser("finding")
    review_finding_sub = review_finding.add_subparsers(dest="review_finding_command", required=True)
    review_finding_update = review_finding_sub.add_parser("update")
    review_finding_update.add_argument("--finding", required=True)
    review_finding_update.add_argument("--status", choices=["unresolved", "addressed", "accepted-risk"], required=True)
    review_finding_update.add_argument("--reason", required=True)
    review_finding_update.add_argument("--actor", choices=["human", "ai"], required=True)
    review_finding_update.add_argument("--human-confirm", action="store_true")
    review_finding_update.add_argument("--decision-note", default="")
    review_finding_update.add_argument("--last-seen-event-id", default="")
    review_finding_update.add_argument("--context-token", default="")
    review_finding_update.set_defaults(func=handlers.cmd_review_finding_update)


def register_verification(sub: argparse._SubParsersAction, handlers: ModuleType) -> None:
    verification = sub.add_parser("verification")
    verification_sub = verification.add_subparsers(dest="verification_command", required=True)
    verification_run = verification_sub.add_parser("run")
    verification_run.add_argument("--task", required=True)
    verification_run.add_argument("--command", required=True)
    verification_run.add_argument("--mode", choices=["quick", "targeted", "full"], default="targeted")
    verification_run.add_argument("--snapshot", choices=["fast", "full", "none", "audit"], default="fast")
    verification_run.add_argument("--timeout", type=float, default=300.0)
    verification_run.set_defaults(func=handlers.cmd_verification_run)

    evidence = sub.add_parser("evidence")
    evidence_sub = evidence.add_subparsers(dest="evidence_command", required=True)
    evidence_show = evidence_sub.add_parser("show")
    evidence_show.add_argument("--task", required=True)
    evidence_show.add_argument("--ai", action="store_true", default=True)
    evidence_show.add_argument("--format", choices=["text", "json"], default="text")
    evidence_show.set_defaults(func=handlers.cmd_evidence_show)
