from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from .cli import (
    AGENT_TARGET_FILES,
    LEGACY_AGENT_TARGET_FILES,
    NILO_BLOCK_BEGIN,
    NILO_BLOCK_END,
    NILO_GENERATED_MARKER,
    NILO_RUNTIME_INSTRUCTION_PATH,
    build_agent_instruction_block,
)
from .gitmeta import git_output


@dataclass(frozen=True)
class AgentInstallationResult:
    updated_paths: tuple[str, ...]
    warnings: tuple[str, ...]


def generated_file_header() -> str:
    return f"{NILO_GENERATED_MARKER}\n\n"


def display_path(path: Path, cwd: Path) -> str:
    try:
        return path.relative_to(cwd).as_posix()
    except ValueError:
        return path.as_posix()


def git_exclude_path(cwd: Path) -> Path | None:
    code, out, _ = git_output(["rev-parse", "--git-path", "info/exclude"], cwd)
    if code != 0 or not out.strip():
        return None
    path = Path(out.strip())
    return path if path.is_absolute() else cwd / path


def _write_generated_file(
    path: Path,
    content: str,
    *,
    cwd: Path,
    force: bool = False,
    warn_unmanaged: bool = True,
) -> tuple[str | None, str | None]:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if NILO_GENERATED_MARKER not in current and not force:
            warning = (
                f"not overwriting unmanaged local file: {path.name}"
                if warn_unmanaged
                else None
            )
            return None, warning
        if current == content:
            return None, None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return display_path(path, cwd), None


def _ensure_git_exclude_entries(cwd: Path) -> tuple[str | None, str | None]:
    path = git_exclude_path(cwd)
    if path is None:
        return None, "not a git work tree; skipping .git/info/exclude update"
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = current.splitlines()
    comment = "# Nilo local runtime files"
    required = [".nilo/", "CLAUDE.local.md", "AGENTS.override.md"]
    comparable = {line.strip() for line in lines}
    missing = [entry for entry in required if entry.strip() not in comparable]
    if not missing:
        return None, None
    if comment not in comparable:
        missing.insert(0, comment)
    prefix = current
    if prefix and not prefix.endswith(("\n", "\r")):
        prefix += "\n"
    path.write_text(prefix + "\n".join(missing) + "\n", encoding="utf-8")
    return ".git/info/exclude", None


def install_agent_runtime_files(
    project: dict,
    targets: list[str],
    *,
    cwd: Path | None = None,
    warn_unmanaged: bool = True,
) -> AgentInstallationResult:
    root = cwd or Path.cwd()
    runtime_body = build_agent_instruction_block(project, "all")
    writes = [
        _write_generated_file(
            root / NILO_RUNTIME_INSTRUCTION_PATH,
            generated_file_header() + runtime_body,
            cwd=root,
            force=True,
        )
    ]
    for target in targets:
        if target == "claude-code":
            body = (
                generated_file_header()
                + "# Nilo runtime instructions\n\n"
                + "This file is generated by Nilo and is intentionally local to this working tree.\n"
                + "Do not edit it manually.\n\n"
                + "Read the following Nilo-generated runtime instructions before starting work:\n\n"
                + f"@{NILO_RUNTIME_INSTRUCTION_PATH}\n"
            )
            writes.append(
                _write_generated_file(
                    root / AGENT_TARGET_FILES[target],
                    body,
                    cwd=root,
                    warn_unmanaged=warn_unmanaged,
                )
            )
        elif target == "codex":
            body = (
                generated_file_header()
                + "# Nilo runtime instructions\n\n"
                + "This file is generated by Nilo and is intentionally local to this working tree.\n"
                + "Do not edit it manually.\n\n"
                + runtime_body
            )
            writes.append(
                _write_generated_file(
                    root / AGENT_TARGET_FILES[target],
                    body,
                    cwd=root,
                    warn_unmanaged=warn_unmanaged,
                )
            )
    writes.append(_ensure_git_exclude_entries(root))
    return AgentInstallationResult(
        updated_paths=tuple(path for path, _ in writes if path),
        warnings=tuple(warning for _, warning in writes if warning),
    )


def inspect_agent_runtime_files(cwd: Path | None = None) -> dict:
    root = cwd or Path.cwd()
    warnings: list[str] = []
    for filename in AGENT_TARGET_FILES.values():
        path = root / filename
        if path.exists() and NILO_GENERATED_MARKER not in path.read_text(
            encoding="utf-8"
        ):
            warnings.append(f"unmanaged local instruction file: {filename}")
    legacy_files = legacy_agent_block_files(root)
    warnings.extend(
        f"deprecated Nilo managed block remains in tracked agent file: {path.name}"
        for path in legacy_files
    )
    runtime_path = root / NILO_RUNTIME_INSTRUCTION_PATH
    claude_path = root / AGENT_TARGET_FILES["claude-code"]
    codex_path = root / AGENT_TARGET_FILES["codex"]
    exclude_path = git_exclude_path(root)
    return {
        "checks": {
            NILO_RUNTIME_INSTRUCTION_PATH: runtime_path.exists(),
            AGENT_TARGET_FILES["claude-code"]: claude_path.exists()
            and f"@{NILO_RUNTIME_INSTRUCTION_PATH}"
            in claude_path.read_text(encoding="utf-8"),
            AGENT_TARGET_FILES["codex"]: codex_path.exists()
            and NILO_BLOCK_BEGIN in codex_path.read_text(encoding="utf-8"),
            ".git/info/exclude": bool(
                exclude_path
                and exclude_path.exists()
                and ".nilo/" in exclude_path.read_text(encoding="utf-8")
            ),
        },
        "warnings": warnings,
        "legacy_files": legacy_files,
    }


def legacy_agent_block_files(cwd: Path | None = None) -> list[Path]:
    root = cwd or Path.cwd()
    return [
        path
        for filename in LEGACY_AGENT_TARGET_FILES.values()
        if (path := root / filename).exists()
        and NILO_BLOCK_BEGIN in path.read_text(encoding="utf-8")
    ]


def remove_nilo_managed_block(text: str) -> str:
    begin = text.find(NILO_BLOCK_BEGIN)
    end = text.find(NILO_BLOCK_END)
    if begin == -1 and end == -1:
        return text
    if begin == -1 or end == -1 or end < begin:
        raise ValueError("malformed Nilo managed block")
    end += len(NILO_BLOCK_END)
    before = text[:begin].rstrip()
    after = text[end:].lstrip()
    if before and after:
        return before + "\n\n" + after
    if before:
        return before + "\n"
    return after


def migrate_legacy_agent_blocks(
    project: dict,
    *,
    cwd: Path | None = None,
    write_text: Callable[[Path, str], None] | None = None,
) -> AgentInstallationResult:
    root = cwd or Path.cwd()
    files = legacy_agent_block_files(root)
    result = install_agent_runtime_files(project, list(AGENT_TARGET_FILES), cwd=root)
    writer = write_text or (lambda path, text: path.write_text(text, encoding="utf-8"))
    migrated: list[str] = []
    for path in files:
        writer(path, remove_nilo_managed_block(path.read_text(encoding="utf-8")))
        migrated.append(display_path(path, root))
    return AgentInstallationResult(
        updated_paths=result.updated_paths + tuple(migrated),
        warnings=result.warnings,
    )
