from __future__ import annotations

import argparse
import locale
import subprocess
import sys
from pathlib import Path

from . import __version__
from .cli_support import cli_quote, make_id, read_text_or_exit
from .design_residue import parse_design_residue
from .failure import deterministic_id
from .gitmeta import git_output, head_commit
from .guard import evaluate_evidence
from .instruction import build_autoscore_prompt, build_instruction, build_review_prompt, build_understanding_prompt
from .project_model import default_project_row, project_row_from_args
from .quality import parse_quality_review
from .quality_logic import (
    normalize_required_scores,
    parse_scores,
    required_scores_for_task,
    validate_known_scores,
    validate_required_scores,
)
from .report import claimed_status, extract_changed_files
from .roadmap_render import (
    render_roadmap_assess_markdown,
    render_roadmap_discuss_markdown,
    render_roadmap_task_plan_markdown,
    roadmap_revision_source_label,
    task_create_command,
    task_plan_candidates,
)
from .secret import mask_secrets
from .store import Store
from .task_logic import completion_status, is_task_completed_status, outcome_status, projected_task_status, require_ai_completion_evidence, split_task_specs
from .timeutil import now_iso
from .update_check import auto_update_notice
from .verification import run_local_verification


AGENT_TARGET_FILES = {
    "codex": "AGENTS.override.md",
    "claude-code": "CLAUDE.local.md",
}
LEGACY_AGENT_TARGET_FILES = {
    "codex": "AGENTS.md",
    "claude-code": "CLAUDE.md",
}
NILO_RUNTIME_INSTRUCTION_PATH = ".nilo/agent-instructions.md"
NILO_GENERATED_MARKER = "<!-- Generated by Nilo. Do not edit manually. -->"
NILO_BLOCK_BEGIN = "<!-- BEGIN NILO MANAGED BLOCK -->"
NILO_BLOCK_END = "<!-- END NILO MANAGED BLOCK -->"


def nilo_version() -> str:
    return __version__


def add_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--db", type=Path, default=None, help="SQLite database path. Defaults to .nilo/nilo.db")


def requires_understanding_gate(task: dict) -> bool:
    if task["task_type"] in ("research", "design", "review", "verification", "documentation"):
        return False
    return bool(task["requires_understanding_check"]) or task["risk_level"] == "high"


def understanding_approved(store: Store, task_id: str) -> bool:
    latest = store.latest_for_task("understanding_checks", task_id)
    return bool(latest and latest["status"] == "approved_to_implement")


def prompt_quality_review(args: argparse.Namespace) -> tuple[str, list[str], list[str]]:
    print("quality_summary:")
    summary = input("> ").strip()
    issues: list[str] = []
    print("quality_issues: enter one issue per line; submit an empty line to finish")
    while True:
        issue = input("> ").strip()
        if not issue:
            break
        issues.append(issue)
    scores = list(args.score or [])
    print("quality_scores: enter key=value; submit an empty line to finish")
    while True:
        score = input("> ").strip()
        if not score:
            break
        scores.append(score)
    return summary, issues, scores


def print_quality_review(review: dict, prefix: str = "") -> None:
    print(f"{prefix}latest_quality_review: {review['id']} ({review['reviewer']})")
    print(f"{prefix}quality_summary: {review['summary']}")
    if review["issues"]:
        print(f"{prefix}quality_issues:")
        for issue in review["issues"]:
            print(f"{prefix}- {issue}")
    if review["scores"]:
        print(f"{prefix}quality_scores:")
        for key, score in review["scores"].items():
            print(f"{prefix}- {key}: {score}")




























































def git_commit_log(cwd: Path, base_commit: str, latest_head: str) -> list[dict]:
    if base_commit == latest_head:
        return []
    completed = subprocess.run(
        ["git", "log", "--format=%H%x00%s", f"{base_commit}..{latest_head}"],
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        return []
    commits = []
    for line in completed.stdout.splitlines():
        if not line.strip():
            continue
        commit_hash, _, subject = line.partition("\x00")
        commits.append({"hash": commit_hash, "subject": subject})
    return commits


def git_changed_files(cwd: Path) -> list[str]:
    completed = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        return []
    files: list[str] = []
    for line in completed.stdout.splitlines():
        if not line.strip():
            continue
        path = line[3:].strip()
        if " -> " in path:
            path = path.split(" -> ", 1)[1].strip()
        if path:
            files.append(path.replace("\\", "/"))
    return sorted(set(files))


def commit_changed_files(cwd: Path, files: list[str], message: str) -> tuple[int, str, str]:
    add_code, _, add_err = git_output(["add", "--", *files], cwd)
    if add_code != 0:
        return add_code, "", add_err
    return git_output(["commit", "-m", message], cwd)
























def markdown_title(markdown: str) -> str:
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and not stripped.startswith("##"):
            return stripped[2:].strip()
    return ""


def markdown_sections(markdown: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current = ""
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            current = stripped.lstrip("#").strip().lower()
            sections.setdefault(current, [])
            continue
        if current:
            sections[current].append(line)
    return sections


def section_text(sections: dict[str, list[str]], names: tuple[str, ...]) -> str:
    for name in names:
        lines = sections.get(name.lower())
        if lines is not None:
            text = "\n".join(line.strip() for line in lines).strip()
            if text:
                return text
    return ""


def section_bullets(sections: dict[str, list[str]], names: tuple[str, ...]) -> list[str]:
    for name in names:
        lines = sections.get(name.lower())
        if lines is None:
            continue
        bullets = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith(("- ", "* ")):
                bullets.append(stripped[2:].strip())
        if bullets:
            return bullets
    return []


def parse_roadmap_proposal(markdown: str) -> dict:
    sections = markdown_sections(markdown)
    return {
        "title": markdown_title(markdown),
        "intent": section_text(sections, ("Intent", "目的", "Rationale", "理由")),
        "success_criteria": section_bullets(sections, ("Success Criteria", "成功条件", "Acceptance Criteria")),
        "non_goals": section_bullets(sections, ("Non Goals", "Non-goals", "非目的")),
        "autonomy_scope": section_bullets(sections, ("Autonomy Scope", "AI に任せてよい範囲", "Scope")),
        "review_gates": section_bullets(sections, ("Review Gates", "人間レビューが必要", "人間レビューが必要な境界")),
        "evidence_policy": section_bullets(sections, ("Evidence Policy", "証跡ポリシー")),
    }


def build_agent_instruction_block(project: dict, target: str = "codex") -> str:
    from .project_boundary import project_boundary_prompt, resolve_project_boundary

    project_id = project["id"]
    boundary = resolve_project_boundary()
    boundary_prompt = project_boundary_prompt(boundary)
    return f"""{NILO_BLOCK_BEGIN}
## Nilo 必須プロトコル

このプロジェクトでは Nilo を AI 作業の状態管理装置として使う。

{boundary_prompt}

Normal work:
- 作業開始と現在地確認は `nilo status --ai --project {project_id}` を使う。
- `nilo next --project {project_id}` の先頭 action だけに従う。
- evidence が stale / missing / failed の場合は完了扱いしない。
- unresolved review finding がある場合は完了扱いしない。
- 検証後は `nilo check` で verification を記録する。
- 最終完了判断、commit、force、roadmap close は人間が行う。

Review handoff:
- 別エージェントへのレビュー依頼、reviewer worker、MCP 経由の証跡記録が必要な場合だけ、利用可能な Nilo MCP tool を使う。
- MCP は通常入口ではない。必要な連携場面でだけ使う。

MCP identity guard:
- MCP tool が呼べる場合でも、それだけで正しい Nilo 状態とは判断しない。
- MCP を使う前に identity の repository / project / git_root / db_path が現在作業中のリポジトリと一致しているか確認する。
- `expected_project` は通常 repository directory name を渡す repository identity guard であり、DB 内の任意 project id ではない。
- 不一致時の `repository_mismatch` は通常 status payload を返さない。
- 複数 repository を同時に扱う場合、MCP を暗黙の DB で呼ばず `project_root` または `workspace` を指定する。
- 優先順位は `project_root`、`workspace`、MCP server の default cwd。
- 対象 root が分かっているなら、人間に質問せず `project_root` を指定して再試行する。
- MCP response の identity を確認し、resolved repository / db_path が対象 repository と一致しない結果は使わない。
- 一致しない場合はその MCP 結果を使わず、人間に質問せず CLI fallback を使う。
- fallback: 対象 repository の作業ディレクトリで `nilo status --ai --project {project_id}`、続けて `nilo next --project {project_id}`。

大きな作業の扱い:
- 実装前に、その指示が小さい作業か大きい作業かを判定する。
- 小さく明確な作業だけ、通常 task として進める。
- 複数ファイルだけでは roadmap 扱いにしない。ひとまとまりの明確なバグ修正は通常 task として進める。
- DB schema/migration、CLI、AI向け出力、docs/tests、安全性に関わる作業は、複数機能・複数実装トラック・不明確な範囲などの広さがある場合に roadmap に通す。
- 大きな作業は `nilo roadmap discuss`、人間の `nilo roadmap accept`、`nilo roadmap task-plan` の順で分解してから進める。

質問抑制:
- Nilo の出力や状態から安全に一意推定できる不足値は人間に質問しない。
- release recipe の `target_version` は現在バージョンと最新 git tag が一致する場合、または SemVer tag が無く現在バージョンから一意に決まる場合、次 patch を採用して進める。
- 質問してよいのは候補が複数、状態矛盾、公開・破壊的操作の直前確認が必要な場合だけ。

詳細は `nilo help ai` を参照する。
{NILO_BLOCK_END}
"""



















































from .project_logic import (
    accepted_roadmap_commitments,
    auto_close_ready_roadmap_commitments,
    closed_roadmap_commitments,
    command_covers_expected_test,
    command_runs_broad_test_suite,
    diff_aware_verification_summary,
    expected_test_paths_for_file,
    handson_language,
    handson_text,
    human_recipe_provenance_label,
    human_roadmap_summary,
    human_roadmap_path_for_project,
    next_actions_for_task,
    normalize_command_path,
    ordered_roadmap_commitments,
    pending_roadmap_revisions,
    pending_roadmap_revision_summaries,
    print_human_project_status,
    print_project_summary_text,
    print_roadmap_agent_next_actions,
    print_roadmap_agent_state,
    project_commit_mapping,
    project_current_phase,
    project_design_residue,
    project_level_next_actions,
    project_roadmap_position,
    project_summary_data,
    project_tasks_and_statuses,
    project_work_state,
    recent_project_history,
    recipe_provenance_summary,
    recipe_completion_warnings,
    recipe_handoff_export_data,
    recipe_handoff_import_data,
    related_tasks_for_commitment,
    render_handson_active_task_next_steps,
    render_handson_markdown,
    render_handson_next_action,
    render_handson_roadmap_position,
    roadmap_agent_next_actions,
    roadmap_agent_state,
    roadmap_assessments,
    roadmap_commitment_assessment,
    roadmap_proposal_path_for_commitment,
    roadmap_task_evidence,
    task_next_actions,
    task_status_counts,
    unexecuted_verifications_for_task,
    unresolved_blocking_review_findings,
    verification_snapshot_policy_lines,
    verification_snapshot_policy_summary,
    verification_summary,
    verification_working_tree_state,
    verification_working_tree_summary,
    write_handson_markdown,
)
from .cli_handlers.backup import cmd_backup, cmd_backups, cmd_backups_prune, cmd_restore
from .cli_handlers.mcp import cmd_mcp_doctor, cmd_mcp_ping, cmd_mcp_reviewer_claim, cmd_mcp_reviewer_start, cmd_mcp_reviewer_worker, cmd_mcp_serve
from .cli_handlers.overdrive import cmd_roadmap_execute, cmd_run
from .cli_handlers.project import cmd_project_create, cmd_project_export_handson, cmd_project_export_recipes, cmd_project_import_recipes, cmd_project_status, cmd_project_summary
from .cli_handlers.facade import (
    cmd_facade_check,
    cmd_facade_done,
    cmd_facade_next,
    cmd_facade_reject,
    cmd_facade_report,
    cmd_facade_start,
    cmd_facade_status,
)
from .cli_handlers.failure import cmd_failure_ignore, cmd_failure_list, cmd_failure_resolve, cmd_failure_show, cmd_failure_summary
from .cli_handlers.quality import (
    cmd_quality_autoscore_import,
    cmd_quality_autoscore_prepare,
    cmd_quality_quick,
    cmd_quality_schema_list,
    cmd_quality_schema_set,
    cmd_review_dispatch,
    cmd_review_doctor,
    cmd_review_human_launch_claude,
    cmd_review_init,
    cmd_review_delegate,
    cmd_review_import,
    cmd_review_finding_update,
    cmd_review_prepare,
    cmd_review_quick,
    cmd_review_request,
    cmd_review_status,
    cmd_review_template,
    cmd_review_wait,
    cmd_review_withdraw,
)
from .cli_handlers.recipe import cmd_recipe_doctor, cmd_recipe_list, cmd_recipe_run, cmd_recipe_show
from .cli_handlers.roadmap import (
    cmd_roadmap_accept,
    cmd_roadmap_adopt,
    cmd_roadmap_assess,
    cmd_roadmap_close,
    cmd_roadmap_discuss,
    cmd_roadmap_export,
    cmd_roadmap_import,
    cmd_roadmap_reject,
    cmd_roadmap_status,
    cmd_roadmap_summary,
    cmd_roadmap_task_plan,
)
from .cli_handlers.task import (
    cmd_evidence_show,
    cmd_review_show,
    cmd_task_complete,
    cmd_task_create,
    cmd_task_list,
    cmd_task_split,
    cmd_task_start,
    cmd_task_status,
    cmd_task_update,
)
from .cli_handlers.todo import cmd_todo_add, cmd_todo_list, cmd_todo_promote, cmd_todo_show, cmd_todo_start, cmd_todo_triage
from .cli_handlers.workflow import cmd_agent_install, cmd_doctor, cmd_init, cmd_instruct, cmd_migrate, cmd_outcome_record, cmd_report_import, cmd_understanding_approve, cmd_understanding_import, cmd_understanding_prepare, cmd_verification_run
from .cli_handlers.workflow import cmd_doctor_ai_context, cmd_help_ai
from .cli_handlers.workflow import cmd_update_check, cmd_upgrade
from .cli_handlers.workspace import cmd_workspace_add, cmd_workspace_list, cmd_workspace_remove, cmd_workspace_show


def build_parser() -> argparse.ArgumentParser:
    from .cli_parsers import build_parser as build_cli_parser

    return build_cli_parser(add_common, sys.modules[__name__])


TOP_LEVEL_COMMANDS = {
    "agent",
    "backup",
    "backups",
    "check",
    "done",
    "doctor",
    "evidence",
    "failure",
    "help",
    "init",
    "instruct",
    "migrate",
    "mcp",
    "next",
    "outcome",
    "project",
    "quality",
    "reject",
    "restore",
    "recipe",
    "report",
    "review",
    "roadmap",
    "run",
    "start",
    "status",
    "task",
    "todo",
    "understanding",
    "update-check",
    "upgrade",
    "verification",
    "workspace",
}


UPDATE_NOTICE_COMMANDS = {
    "doctor",
    "init",
    "next",
    "review",
    "status",
}


def route_natural_language_intent(argv: list[str]) -> bool:
    remaining = list(argv)
    db_path: Path | None = None
    if len(remaining) >= 2 and remaining[0] == "--db":
        db_path = Path(remaining[1])
        remaining = remaining[2:]
    if not remaining or remaining[0] in TOP_LEVEL_COMMANDS or remaining[0].startswith("-"):
        return False

    utterance = " ".join(remaining).strip()
    normalized = utterance.casefold()
    wants_claude_code = "claude" in normalized or "cluade" in normalized
    wants_codex = "codex" in normalized
    wants_review = "レビュー" in utterance or "review" in normalized
    if not ((wants_claude_code or wants_codex) and wants_review):
        return False

    reviewer = "claude-code" if wants_claude_code else "codex"
    wants_lightweight = any(marker in normalized for marker in ["quick", "light", "軽く", "軽い", "軽量", "さっと", "簡単"])
    wants_formal = any(marker in normalized for marker in ["dispatch", "formal", "gate", "completion", "正式", "完了前"])
    if wants_lightweight and not wants_formal:
        cmd_review_quick(
            argparse.Namespace(
                db=db_path,
                project=Path.cwd().name,
                task=None,
                actor="codex",
                reviewer=reviewer,
                reason=utterance,
                should_import=True,
                timeout=120.0,
                auto_configure=True,
                config=None,
            )
        )
        return True

    cmd_review_dispatch(
        argparse.Namespace(
            db=db_path,
            project=Path.cwd().name,
            task=None,
            actor="codex",
            reviewer=reviewer,
            reason=utterance,
            auto_start=True,
            auto_configure=True,
            config=None,
        )
    )
    return True


def main(argv: list[str] | None = None) -> None:
    raw_argv = list(sys.argv[1:] if argv is None else argv)
    if route_natural_language_intent(raw_argv):
        return
    parser = build_parser()
    args = parser.parse_args(raw_argv)
    args.func(args)
    if args.command in UPDATE_NOTICE_COMMANDS:
        notice = auto_update_notice()
        if notice:
            print()
            print(notice)
