from __future__ import annotations

import argparse
import json
import locale
import subprocess
import sys
from pathlib import Path

from . import __version__
from .cli_support import cli_quote, make_id, read_text_or_exit
from .design_residue import parse_design_residue
from .failure import deterministic_id
from .gitmeta import git_output, head_commit
from .guard import evaluate_evidence
from .instruction import build_autoscore_prompt, build_instruction, build_review_prompt, build_understanding_prompt
from .project_model import default_project_row, project_row_from_args
from .quality import parse_quality_review
from .quality_logic import (
    normalize_required_scores,
    parse_scores,
    required_scores_for_task,
    validate_known_scores,
    validate_required_scores,
)
from .report import claimed_status, extract_changed_files
from .roadmap_render import (
    render_roadmap_assess_markdown,
    render_roadmap_discuss_markdown,
    render_roadmap_task_plan_markdown,
    roadmap_revision_source_label,
    task_create_command,
    task_plan_candidates,
)
from .secret import mask_secrets
from .store import Store
from .task_logic import completion_status, is_task_completed_status, outcome_status, projected_task_status, require_ai_completion_evidence, split_task_specs
from .timeutil import now_iso
from .update_check import auto_update_notice
from .verification import run_local_verification


AGENT_TARGET_FILES = {
    "codex": "AGENTS.override.md",
    "claude-code": "CLAUDE.local.md",
}
LEGACY_AGENT_TARGET_FILES = {
    "codex": "AGENTS.md",
    "claude-code": "CLAUDE.md",
}
NILO_RUNTIME_INSTRUCTION_PATH = ".nilo/agent-instructions.md"
NILO_GENERATED_MARKER = "<!-- Generated by Nilo. Do not edit manually. -->"
NILO_BLOCK_BEGIN = "<!-- BEGIN NILO MANAGED BLOCK -->"
NILO_BLOCK_END = "<!-- END NILO MANAGED BLOCK -->"


def nilo_version() -> str:
    return __version__


def add_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--db", type=Path, default=None, help="SQLite database path. Defaults to .nilo/nilo.db")


def requires_understanding_gate(task: dict) -> bool:
    if task["task_type"] in ("research", "design", "review", "verification", "documentation"):
        return False
    return bool(task["requires_understanding_check"]) or task["risk_level"] == "high"


def understanding_approved(store: Store, task_id: str) -> bool:
    latest = store.latest_for_task("understanding_checks", task_id)
    return bool(latest and latest["status"] == "approved_to_implement")


def prompt_quality_review(args: argparse.Namespace) -> tuple[str, list[str], list[str]]:
    print("quality_summary:")
    summary = input("> ").strip()
    issues: list[str] = []
    print("quality_issues: enter one issue per line; submit an empty line to finish")
    while True:
        issue = input("> ").strip()
        if not issue:
            break
        issues.append(issue)
    scores = list(args.score or [])
    print("quality_scores: enter key=value; submit an empty line to finish")
    while True:
        score = input("> ").strip()
        if not score:
            break
        scores.append(score)
    return summary, issues, scores


def print_quality_review(review: dict, prefix: str = "") -> None:
    print(f"{prefix}latest_quality_review: {review['id']} ({review['reviewer']})")
    print(f"{prefix}quality_summary: {review['summary']}")
    if review["issues"]:
        print(f"{prefix}quality_issues:")
        for issue in review["issues"]:
            print(f"{prefix}- {issue}")
    if review["scores"]:
        print(f"{prefix}quality_scores:")
        for key, score in review["scores"].items():
            print(f"{prefix}- {key}: {score}")




























































def git_commit_log(cwd: Path, base_commit: str, latest_head: str) -> list[dict]:
    if base_commit == latest_head:
        return []
    completed = subprocess.run(
        ["git", "log", "--format=%H%x00%s", f"{base_commit}..{latest_head}"],
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        return []
    commits = []
    for line in completed.stdout.splitlines():
        if not line.strip():
            continue
        commit_hash, _, subject = line.partition("\x00")
        commits.append({"hash": commit_hash, "subject": subject})
    return commits


def git_changed_files(cwd: Path) -> list[str]:
    completed = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        return []
    files: list[str] = []
    for line in completed.stdout.splitlines():
        if not line.strip():
            continue
        path = line[3:].strip()
        if " -> " in path:
            path = path.split(" -> ", 1)[1].strip()
        if path:
            files.append(path.replace("\\", "/"))
    return sorted(set(files))


def commit_changed_files(cwd: Path, files: list[str], message: str) -> tuple[int, str, str]:
    add_code, _, add_err = git_output(["add", "--", *files], cwd)
    if add_code != 0:
        return add_code, "", add_err
    return git_output(["commit", "-m", message], cwd)
























def markdown_title(markdown: str) -> str:
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and not stripped.startswith("##"):
            return stripped[2:].strip()
    return ""


def markdown_sections(markdown: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current = ""
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            current = stripped.lstrip("#").strip().lower()
            sections.setdefault(current, [])
            continue
        if current:
            sections[current].append(line)
    return sections


def section_text(sections: dict[str, list[str]], names: tuple[str, ...]) -> str:
    for name in names:
        lines = sections.get(name.lower())
        if lines is not None:
            text = "\n".join(line.strip() for line in lines).strip()
            if text:
                return text
    return ""


def section_bullets(sections: dict[str, list[str]], names: tuple[str, ...]) -> list[str]:
    for name in names:
        lines = sections.get(name.lower())
        if lines is None:
            continue
        bullets = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith(("- ", "* ")):
                bullets.append(stripped[2:].strip())
        if bullets:
            return bullets
    return []


def parse_roadmap_proposal(markdown: str) -> dict:
    sections = markdown_sections(markdown)
    return {
        "title": markdown_title(markdown),
        "intent": section_text(sections, ("Intent", "目的", "Rationale", "理由")),
        "success_criteria": section_bullets(sections, ("Success Criteria", "成功条件", "Acceptance Criteria")),
        "non_goals": section_bullets(sections, ("Non Goals", "Non-goals", "非目的")),
        "autonomy_scope": section_bullets(sections, ("Autonomy Scope", "AI に任せてよい範囲", "Scope")),
        "review_gates": section_bullets(sections, ("Review Gates", "人間レビューが必要", "人間レビューが必要な境界")),
        "evidence_policy": section_bullets(sections, ("Evidence Policy", "証跡ポリシー")),
    }


def build_agent_instruction_block(project: dict, target: str = "codex") -> str:
    from .project_language import project_primary_language
    from .project_boundary import project_boundary_prompt, resolve_project_boundary

    project_id = project["id"]
    primary_language = project_primary_language(project)
    boundary = resolve_project_boundary()
    boundary_prompt = project_boundary_prompt(boundary)
    return f"""{NILO_BLOCK_BEGIN}
## Nilo 必須プロトコル

{boundary_prompt}

Normal work:
- 開始は `nilo status --ai --project {project_id}`。
- `nilo next --project {project_id}` の先頭 action だけに従う。
- active recipe 中は recipe のみ。
- 保存文面は primary_language={primary_language}。command/path/status/enum/JSONは原文。
- release公開操作は明示承認待ち。
- 検証済み dirty tree 由来 commit は stale 扱いしない。
- evidence が stale / missing / failed の場合は完了扱いしない。
- unresolved review finding がある場合は完了扱いしない。
- 検証後は `nilo check --task <task_id> "..."`。省略は一意target。
- 最終完了/commit/force/roadmap close は人間が行う。`--human-acceptance`。

Review handoff:
- レビュー依頼、reviewer worker、MCP 経由の証跡記録だけ Nilo MCP tool を使う。MCP は通常入口ではない。
- AIレビュー依頼は必ず high-level `dispatch_review` を第一候補にする。無ければ `register_reviewer` -> `claim_next_review` -> `import_review_result`。
- `claude` / `codex` CLI の直接起動、`nilo review dispatch` / `quick` は CLI reviewer process fallback/human-launch 専用。
- review help に従う。例: `nilo review status --task <task_id> --format json`。`review status` に `--project` は付けない。
MCP identity guard:
- MCP tool 可でも正しい Nilo 状態とは判断しない。使用前に identity の repository / project / git_root / db_path が現在 repo と一致するか確認。
- `expected_project` は repository directory name 用。複数 repo は `project_root` か `workspace`。
- MCP response の repository / db_path 不一致は使わず CLI fallback。
- fallback: `nilo status --ai --project {project_id}` -> `nilo next --project {project_id}`。

大きな作業の扱い:
- 実装前に小さい作業か大きい作業かを判定する。
- 小さく明確なら通常 task。複数ファイルだけでは roadmap 扱いしない。
- 複数タスク/コミット、DB schema、状態遷移、リリース基盤など広い変更だけ Roadmap/Epic。
- Epic 必要時は停止し、承認まで roadmap revision / acceptance / task plan を進めない。
- 大作業は自動 roadmap 化しない。承認後だけ `nilo roadmap discuss` -> `import`/`adopt` -> 人間承認 -> `nilo roadmap task-plan`。

質問抑制:
- Nilo 出力や状態から一意推定できる不足値は質問しない。
- release recipe の `target_version` は一意なら次 patch。
- 質問は候補複数、状態矛盾、公開・破壊的操作直前だけ。

詳細: `nilo help ai`
{NILO_BLOCK_END}
"""



















































from .project_logic import (
    accepted_roadmap_commitments,
    auto_close_ready_roadmap_commitments,
    closed_roadmap_commitments,
    command_covers_expected_test,
    command_runs_broad_test_suite,
    diff_aware_verification_summary,
    expected_test_paths_for_file,
    handson_language,
    handson_text,
    human_recipe_provenance_label,
    human_roadmap_summary,
    human_roadmap_path_for_project,
    next_actions_for_task,
    normalize_command_path,
    ordered_roadmap_commitments,
    pending_roadmap_revisions,
    pending_roadmap_revision_summaries,
    project_commit_mapping,
    project_current_phase,
    project_design_residue,
    project_level_next_actions,
    project_roadmap_position,
    project_summary_data,
    project_tasks_and_statuses,
    project_work_state,
    recent_project_history,
    recipe_provenance_summary,
    recipe_completion_warnings,
    recipe_handoff_export_data,
    recipe_handoff_import_data,
    related_tasks_for_commitment,
    render_handson_active_task_next_steps,
    render_handson_markdown,
    render_handson_next_action,
    render_handson_roadmap_position,
    roadmap_agent_next_actions,
    roadmap_agent_state,
    roadmap_assessments,
    roadmap_commitment_assessment,
    roadmap_proposal_path_for_commitment,
    roadmap_prioritized_project_active_tasks,
    roadmap_task_evidence,
    task_next_actions,
    task_status_counts,
    unexecuted_verifications_for_task,
    unresolved_blocking_review_findings,
    verification_snapshot_policy_lines,
    verification_snapshot_policy_summary,
    verification_summary,
    verification_working_tree_state,
    verification_working_tree_summary,
    write_handson_markdown,
)
from .project_render import print_human_project_status, print_project_summary_text, print_roadmap_agent_next_actions, print_roadmap_agent_state
def build_parser() -> argparse.ArgumentParser:
    from .cli_parsers import build_parser as build_cli_parser
    from .cli_handlers import registry as handler_registry

    return build_cli_parser(add_common, handler_registry)


TOP_LEVEL_COMMANDS = {
    "agent",
    "backup",
    "backups",
    "check",
    "done",
    "doctor",
    "evidence",
    "failure",
    "help",
    "init",
    "instruct",
    "migrate",
    "mcp",
    "next",
    "outcome",
    "project",
    "quality",
    "queue",
    "reject",
    "restore",
    "recipe",
    "report",
    "review",
    "roadmap",
    "run",
    "start",
    "status",
    "task",
    "test",
    "todo",
    "understanding",
    "update-check",
    "upgrade",
    "verification",
    "view",
    "workspace",
}


UPDATE_NOTICE_EXCLUDED_COMMANDS = TOP_LEVEL_COMMANDS - {"doctor", "update-check"}


def should_show_update_notice(args: argparse.Namespace) -> bool:
    if bool(getattr(args, "json", False)) or bool(getattr(args, "ai", False)):
        return False
    command = str(getattr(args, "command", ""))
    return command in TOP_LEVEL_COMMANDS and command not in UPDATE_NOTICE_EXCLUDED_COMMANDS


def route_natural_language_intent(argv: list[str]) -> bool:
    remaining = list(argv)
    db_path: Path | None = None
    if len(remaining) >= 2 and remaining[0] == "--db":
        db_path = Path(remaining[1])
        remaining = remaining[2:]
    if not remaining or remaining[0] in TOP_LEVEL_COMMANDS or remaining[0].startswith("-"):
        return False

    utterance = " ".join(remaining).strip()
    normalized = utterance.casefold()
    wants_claude_code = "claude" in normalized or "cluade" in normalized
    wants_codex = "codex" in normalized
    wants_review = "レビュー" in utterance or "review" in normalized
    if not ((wants_claude_code or wants_codex) and wants_review):
        return False

    reviewer = "claude-code" if wants_claude_code else "codex"
    wants_lightweight = any(marker in normalized for marker in ["quick", "light", "軽く", "軽い", "軽量", "さっと", "簡単"])
    reason = utterance
    if wants_lightweight:
        reason = f"{utterance} (quick requested; quick is local CLI fallback / diagnostics only)"
    project_id = Path.cwd().name
    task_id = natural_language_active_task_id(db_path or Path(".nilo") / "nilo.db", project_id)
    print("review_handoff: use Nilo MCP dispatch_review for normal AI-to-AI review")
    print("review_handoff_reason: natural-language CLI entrypoint cannot call MCP tools directly")
    print(f"reviewer: {reviewer}")
    print(f"project: {project_id}")
    if task_id:
        print(f"task: {task_id}")
    else:
        print("task: unresolved; resolve the active task before calling dispatch_review")
    print(f"reason: {reason}")
    print("mcp_tool: dispatch_review")
    mcp_arguments = {"project_id": project_id, "actor": "codex", "reviewer": reviewer, "reason": reason}
    if task_id:
        mcp_arguments["task_id"] = task_id
    print(f"mcp_arguments: {json.dumps(mcp_arguments, ensure_ascii=False)}")
    print("cli_fallback: use `nilo review dispatch` only after explaining why MCP review workflow is unavailable")
    return True


def natural_language_active_task_id(db_path: Path, project_id: str) -> str:
    if not db_path.exists():
        return ""
    store = Store(db_path)
    try:
        project = store.get("projects", project_id)
        if not project:
            return ""
        tasks, statuses = project_tasks_and_statuses(store, project_id)
        active = [task for task in tasks if not is_task_completed_status(statuses[task["id"]])]
        if len(active) != 1:
            return ""
        return str(active[0]["id"])
    finally:
        store.close()


def main(argv: list[str] | None = None) -> None:
    raw_argv = list(sys.argv[1:] if argv is None else argv)
    if route_natural_language_intent(raw_argv):
        return
    parser = build_parser()
    args = parser.parse_args(raw_argv)
    args.func(args)
    if should_show_update_notice(args):
        notice = auto_update_notice()
        if notice:
            print()
            print(notice)
