from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ..ai_context import AI_CONTEXT_TEXT_MAX_CHARS, project_ai_context, render_ai_context_text
from ..cli import (
    AGENT_TARGET_FILES,
    LEGACY_AGENT_TARGET_FILES,
    NILO_BLOCK_BEGIN,
    NILO_BLOCK_END,
    NILO_GENERATED_MARKER,
    NILO_RUNTIME_INSTRUCTION_PATH,
    build_agent_instruction_block,
    requires_understanding_gate,
    understanding_approved,
)
from ..cli_support import make_id, read_text_or_exit
from ..display_labels import field_label
from ..failure import record_failure_log, summarize_failure_logs
from ..gitmeta import git_output, head_commit
from ..guard import evaluate_evidence
from ..instruction import build_instruction, build_understanding_prompt
from ..project_model import default_project_row
from ..project_boundary import (
    ProjectBoundaryError,
    project_boundary_prompt,
    record_nilo_issue_for_task,
    require_write_fence,
    resolve_project_boundary,
)
from ..snapshot import compact_snapshot, current_git_snapshot, evidence_status
from ..store import Store
from ..task_logic import active_task_completion, completion_audit_issues, outcome_status, unresolved_review_findings
from ..timeutil import now_iso
from ..transitions import (
    TransitionError,
    approve_understanding,
    import_agent_report,
    record_outcome_decision,
    record_verification_run,
)
from ..update_check import check_for_update, is_disabled, update_message
from ..upgrade import run_upgrade
from ..verification import run_local_verification


def cmd_agent_install(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        project = store.get("projects", args.project)
        if not project:
            raise SystemExit(f"project not found: {args.project}")
        targets = list(AGENT_TARGET_FILES) if args.target == "all" else [args.target]
        install_agent_blocks(project, targets)
    finally:
        store.close()


def install_agent_blocks(project: dict, targets: list[str], *, warn_unmanaged: bool = True) -> None:
    runtime_body = build_agent_instruction_block(project, "all")
    write_runtime_instruction_body(runtime_body)
    for target in targets:
        if target == "claude-code":
            write_claude_local_bridge(warn_unmanaged=warn_unmanaged)
        elif target == "codex":
            write_codex_override(runtime_body, warn_unmanaged=warn_unmanaged)
    ensure_nilo_git_exclude_entries()


def generated_file_header() -> str:
    return f"{NILO_GENERATED_MARKER}\n\n"


def write_generated_file(path: Path, content: str, *, force: bool = False, warn_unmanaged: bool = True) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if NILO_GENERATED_MARKER not in current and not force:
            if warn_unmanaged:
                print(f"warning: not overwriting unmanaged local file: {path.name}")
            return False
        if current == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"updated: {display_path(path)}")
    return True


def display_path(path: Path) -> str:
    try:
        return path.relative_to(Path.cwd()).as_posix()
    except ValueError:
        return path.as_posix()


def write_runtime_instruction_body(runtime_body: str, *, force: bool = True) -> bool:
    path = Path.cwd() / NILO_RUNTIME_INSTRUCTION_PATH
    return write_generated_file(path, generated_file_header() + runtime_body, force=force)


def write_claude_local_bridge(*, force: bool = False, warn_unmanaged: bool = True) -> bool:
    body = (
        generated_file_header()
        + "# Nilo runtime instructions\n\n"
        + "This file is generated by Nilo and is intentionally local to this working tree.\n"
        + "Do not edit it manually.\n\n"
        + "Read the following Nilo-generated runtime instructions before starting work:\n\n"
        + f"@{NILO_RUNTIME_INSTRUCTION_PATH}\n"
    )
    return write_generated_file(Path.cwd() / AGENT_TARGET_FILES["claude-code"], body, force=force, warn_unmanaged=warn_unmanaged)


def write_codex_override(runtime_body: str, *, force: bool = False, warn_unmanaged: bool = True) -> bool:
    body = (
        generated_file_header()
        + "# Nilo runtime instructions\n\n"
        + "This file is generated by Nilo and is intentionally local to this working tree.\n"
        + "Do not edit it manually.\n\n"
        + runtime_body
    )
    return write_generated_file(Path.cwd() / AGENT_TARGET_FILES["codex"], body, force=force, warn_unmanaged=warn_unmanaged)


def ensure_nilo_git_exclude_entries() -> None:
    path = git_exclude_path(Path.cwd())
    if path is None:
        print("warning: not a git work tree; skipping .git/info/exclude update")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = current.splitlines()
    comment = "# Nilo local runtime files"
    required = [".nilo/", "CLAUDE.local.md", "AGENTS.override.md"]
    comparable = {line.strip() for line in lines}
    missing = [entry for entry in required if entry.strip() not in comparable]
    if not missing:
        return
    if comment not in comparable:
        missing.insert(0, comment)
    prefix = current
    if prefix and not prefix.endswith(("\n", "\r")):
        prefix += "\n"
    path.write_text(prefix + "\n".join(missing) + "\n", encoding="utf-8")
    print("updated: .git/info/exclude")


def git_exclude_path(cwd: Path) -> Path | None:
    code, out, _ = git_output(["rev-parse", "--git-path", "info/exclude"], cwd)
    if code != 0 or not out.strip():
        return None
    path = Path(out.strip())
    if not path.is_absolute():
        path = cwd / path
    return path


def local_instruction_warnings() -> list[str]:
    warnings: list[str] = []
    for filename in AGENT_TARGET_FILES.values():
        path = Path.cwd() / filename
        if path.exists() and NILO_GENERATED_MARKER not in path.read_text(encoding="utf-8"):
            warnings.append(f"unmanaged local instruction file: {filename}")
    for filename in LEGACY_AGENT_TARGET_FILES.values():
        path = Path.cwd() / filename
        if path.exists() and NILO_BLOCK_BEGIN in path.read_text(encoding="utf-8"):
            warnings.append(f"deprecated Nilo managed block remains in tracked agent file: {filename}")
    return warnings


def legacy_agent_block_files() -> list[Path]:
    files: list[Path] = []
    for filename in LEGACY_AGENT_TARGET_FILES.values():
        path = Path.cwd() / filename
        if path.exists() and NILO_BLOCK_BEGIN in path.read_text(encoding="utf-8"):
            files.append(path)
    return files


def print_legacy_agent_block_guidance(files: list[Path]) -> None:
    if not files:
        return
    names = ", ".join(path.name for path in files)
    print(f"warning: deprecated Nilo managed block remains in tracked agent file(s): {names}")
    print("Nilo no longer updates tracked CLAUDE.md / AGENTS.md files by default.")
    print("To remove the old generated block and refresh local runtime files, run:")
    print("  nilo migrate --apply")


def remove_nilo_managed_block(text: str) -> str:
    begin = text.find(NILO_BLOCK_BEGIN)
    end = text.find(NILO_BLOCK_END)
    if begin == -1 and end == -1:
        return text
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit("malformed Nilo managed block")
    end += len(NILO_BLOCK_END)
    before = text[:begin].rstrip()
    after = text[end:].lstrip()
    if before and after:
        return before + "\n\n" + after
    if before:
        return before + "\n"
    return after


def project_for_current_directory(store: Store) -> dict:
    project_id = Path.cwd().name
    project = store.get("projects", project_id)
    return project if project else default_project_row(project_id, now_iso())


def cmd_doctor(args: argparse.Namespace) -> None:
    project_id = Path.cwd().name
    store = Store(args.db)
    try:
        project = store.get("projects", project_id)
        if not project:
            project = default_project_row(project_id, now_iso())
        if args.fix_local_instructions:
            install_agent_blocks(project, list(AGENT_TARGET_FILES), warn_unmanaged=False)
        warnings = local_instruction_warnings()
        runtime_path = Path.cwd() / NILO_RUNTIME_INSTRUCTION_PATH
        claude_path = Path.cwd() / AGENT_TARGET_FILES["claude-code"]
        codex_path = Path.cwd() / AGENT_TARGET_FILES["codex"]
        exclude_path = git_exclude_path(Path.cwd())
        checks = {
            NILO_RUNTIME_INSTRUCTION_PATH: runtime_path.exists(),
            AGENT_TARGET_FILES["claude-code"]: claude_path.exists() and f"@{NILO_RUNTIME_INSTRUCTION_PATH}" in claude_path.read_text(encoding="utf-8"),
            AGENT_TARGET_FILES["codex"]: codex_path.exists() and NILO_BLOCK_BEGIN in codex_path.read_text(encoding="utf-8"),
            ".git/info/exclude": bool(exclude_path and exclude_path.exists() and ".nilo/" in exclude_path.read_text(encoding="utf-8")),
        }
        for name, ok in checks.items():
            print(f"{name}: {'ok' if ok else '未作成'}")
        for warning in warnings:
            print(f"警告: {warning}")
    finally:
        store.close()


def cmd_doctor_ai_context(args: argparse.Namespace) -> None:
    from .. import mcp_server

    project_id = args.project or Path.cwd().name
    store = Store(args.db)
    try:
        project = store.get("projects", project_id)
        if not project:
            raise SystemExit(f"project not found: {project_id}")
        runtime_body = build_agent_instruction_block(project, "all")
        ai_context = project_ai_context(store, project_id)
        status_body = render_ai_context_text(ai_context, max_chars=AI_CONTEXT_TEXT_MAX_CHARS)
        failure_summary = summarize_failure_logs(store, project_id=project_id, limit=100000)
        failure_summary_lines = [
            f"{field_label('failure_summary')}:",
            f"- {field_label('open_failures')}: {failure_summary['open_failure_count']}",
            f"- {field_label('high_open_failures')}: {failure_summary['high_open_failure_count']}",
        ]
        latest_failure = failure_summary["latest_open_failure"]
        if latest_failure:
            failure_summary_lines.append(f"- {field_label('latest_open_failure')}: {latest_failure['task_id']} {latest_failure['category']}")
        failure_summary_lines.append(f"詳細は `nilo failure list --project {project_id}` を確認してください。")
        failure_summary_chars = len("\n".join(failure_summary_lines))
        long_descriptions = [
            {"name": tool["name"], "length": len(tool.get("description", ""))}
            for tool in mcp_server.TOOLS
            if len(tool.get("description", "")) > 160
        ]
        stale_evidence_count = 0
        unresolved_review_count = 0
        current_snapshot = current_git_snapshot(Path.cwd())
        for task in store.list_where("tasks", "project_id=?", (project_id,)):
            verification_run = store.latest_for_task("verification_runs", task["id"])
            if evidence_status(verification_run, current_snapshot) == "stale":
                stale_evidence_count += 1
            unresolved_review_count += len(unresolved_review_findings(store, task["id"]))
        default_tools = mcp_server.default_tools()
        review_handoff_tools = mcp_server.review_handoff_tools()
        print("AIコンテキスト:")
        print(f"- instruction_chars: {len(runtime_body)}")
        print(f"- mcp_default_tool_count: {len(default_tools)}")
        print(f"- mcp_review_handoff_tool_count: {len(review_handoff_tools)}")
        print(
            "- mcp_review_handoff_tools: "
            + ", ".join(tool["name"] for tool in review_handoff_tools)
        )
        print(f"- long_tool_descriptions: {len(long_descriptions)}")
        for item in long_descriptions[:5]:
            print(f"  - {item['name']}: {item['length']}")
        print(f"- status_ai_chars: {len(status_body)}")
        print(f"- status_ai_max_chars: {AI_CONTEXT_TEXT_MAX_CHARS}")
        print(f"- status_ai_within_budget: {len(status_body) <= AI_CONTEXT_TEXT_MAX_CHARS}")
        print(f"- open_failure_count: {failure_summary['open_failure_count']}")
        print(f"- high_open_failure_count: {failure_summary['high_open_failure_count']}")
        print(f"- failure_summary_chars: {failure_summary_chars}")
        print(f"- stale_evidence_count: {stale_evidence_count}")
        print(f"- unresolved_review_count: {unresolved_review_count}")
    finally:
        store.close()


def cmd_doctor_completions(args: argparse.Namespace) -> None:
    import json
    from ..state_audit import audit_project

    project_id = args.project or Path.cwd().name
    store = Store(args.db)
    try:
        project = store.get("projects", project_id)
        if not project:
            raise SystemExit(f"project not found: {project_id}")
        audit_findings = audit_project(store, project_id)
        findings = [item for item in audit_findings if item["code"].startswith("completion_")]
        result = {"project_id": project_id, "count": len(findings), "findings": findings}
        if getattr(args, "json", False):
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return
        print(f"project: {project_id} ({project['name']})")
        print(f"completion_audit: {len(findings)} issue(s)")
        if findings:
            print("No automatic changes were made. Use `nilo task completion invalidate --completion <id> --reason \"...\"` after human review.")
        for finding in findings:
            print(f"- {finding['entity_type']}={finding['entity_id']} [{finding['severity']}] {finding['code']}: {finding['message']}")
    finally:
        store.close()


def cmd_doctor_state(args: argparse.Namespace) -> None:
    import json
    from ..state_audit import doctor_state

    project_id = args.project or Path.cwd().name
    store = Store(args.db)
    try:
        result = doctor_state(store, project_id, cwd=Path.cwd())
        if getattr(args, "json", False):
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return
        print(f"project: {project_id}")
        print(f"state_audit: {result['count']} finding(s)")
        print("No automatic changes were made.")
        for item in result["findings"]:
            print(f"- [{item['severity']}] {item['code']} {item['entity_type']}={item['entity_id']}: {item['message']}")
            if item.get("remediation"):
                print(f"  remediation: {item['remediation']}")
    finally:
        store.close()


def cmd_doctor_performance(args: argparse.Namespace) -> None:
    import json

    project_id = args.project or Path.cwd().name
    store = Store(args.db)
    try:
        project = store.get("projects", project_id)
        if not project:
            raise SystemExit(f"project not found: {project_id}")
        snapshot = current_git_snapshot(Path.cwd(), mode="full")
        timing = snapshot.get("snapshot_timing") or {}
        result = {
            "project_id": project_id,
            "snapshot_mode": snapshot.get("snapshot_mode", "full"),
            "git_available": bool(snapshot.get("git_available", True)),
            "git_diff_hash_computed": bool(snapshot.get("git_diff_hash_computed", True)),
            "diff_hash_seconds": timing.get("diff_hash_seconds", 0.0),
            "observed_paths": len(snapshot.get("observed_paths") or []),
            "hashed_paths": len(snapshot.get("snapshot_hashed_paths") or []),
            "excluded_paths": len(snapshot.get("snapshot_excluded_paths") or []),
            "large_paths": len(snapshot.get("snapshot_large_paths") or []),
            "binary_paths": len(snapshot.get("snapshot_binary_paths") or []),
            "warnings": snapshot.get("snapshot_warnings") or [],
        }
        if getattr(args, "json", False):
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return
        print(f"project: {project_id} ({project['name']})")
        print("git_snapshot:")
        print(f"- mode: {result['snapshot_mode']}")
        print(f"- diff_hash_seconds: {result['diff_hash_seconds']:.3f}")
        print(f"- observed_paths: {result['observed_paths']}")
        print(f"- hashed_paths: {result['hashed_paths']}")
        print(f"- excluded_paths: {result['excluded_paths']}")
        print(f"- large_paths: {result['large_paths']}")
        print(f"- binary_paths: {result['binary_paths']}")
        for warning in result["warnings"]:
            print(warning)
    finally:
        store.close()


def cmd_doctor_workflow(args: argparse.Namespace) -> None:
    import json
    from ..state_audit import audit_workflow

    project_id = args.project or Path.cwd().name
    store = Store(args.db)
    try:
        if not store.get("projects", project_id):
            raise SystemExit(f"project not found: {project_id}")
        findings = audit_workflow(store, project_id, cwd=Path.cwd())
        result = {"project_id": project_id, "count": len(findings), "findings": findings}
        if getattr(args, "json", False):
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return
        print(f"project: {project_id}")
        print(f"workflow_audit: {len(findings)} finding(s)")
        print("No automatic changes were made.")
        for item in findings:
            print(f"- [{item['severity']}] {item['code']} {item['entity_type']}={item['entity_id']}: {item['message']}")
    finally:
        store.close()


def cmd_doctor_transitions(args: argparse.Namespace) -> None:
    import json

    project_id = args.project or Path.cwd().name
    store = Store(args.db)
    try:
        task_ids = {task["id"] for task in store.list_where("tasks", "project_id=?", (project_id,))}
        events = [
            event
            for event in store.list_where("transition_events", "1=1")
            if event["entity_id"] in task_ids or (isinstance(event.get("related_ids"), dict) and any(value in task_ids for value in event["related_ids"].values()))
        ]
        result = {"project_id": project_id, "count": len(events), "transition_events": events[: args.limit]}
        if getattr(args, "json", False):
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return
        print(f"project: {project_id}")
        print(f"transition_events: {len(events)}")
        for event in events[: args.limit]:
            print(f"- {event['created_at']} {event['transition']} {event['entity_type']}={event['entity_id']} actor={event['actor']} {event['previous_state']} -> {event['new_state']}")
    finally:
        store.close()


def cmd_help_ai(args: argparse.Namespace) -> None:
    print(
        "\n".join(
            [
                "Nilo AI normal work:",
                "- Start with `nilo status --ai`.",
                "- Follow the first action shown by `nilo next`.",
                "- When a recipe/workflow is active, generic continuation commands such as \"進めて\", \"続けて\", or \"next\" continue that workflow only.",
                "- Do not switch to unrelated project tasks unless the user explicitly asks to proceed to another task.",
                "- For release recipes, tag/push/GitHub release/package publish are public operations and require explicit user approval.",
                "- Do not treat commit-created git head changes as stale evidence if the commit was created by Nilo from the verified dirty tree.",
                "- Do not treat stale, missing, or failed evidence as complete.",
                "- Do not treat unresolved review findings as complete.",
                "- After verification, normally record it with `nilo check --task <task_id> \"...\" --mode quick|targeted|full`.",
                "- Omit `--task` only when Nilo can safely infer exactly one unfinished verification target.",
                "- Use quick for narrow smoke checks, targeted for changed modules or focused test groups, and full for releases or broad-risk changes.",
                "- Treat timeouts as guardrails around a chosen scope, not as the main way to make full-suite verification practical.",
                "- Final completion acceptance remains a human decision.",
                "- MCP is not the normal entrypoint; use available Nilo MCP tools only for review handoff, reviewer workers, or MCP-based evidence recording.",
                "- Normal AI review handoff: prefer MCP `dispatch_review`; if unavailable use `register_reviewer` -> `claim_next_review` -> `import_review_result`.",
                "- Do not directly launch `claude`/`codex` CLI, `nilo review dispatch`, or `nilo review quick` unless MCP review workflow is unavailable; explain the CLI reviewer process fallback reason first.",
                "",
                "MCP:",
                "- Do not trust MCP only because it is callable; first confirm its identity matches the current repository.",
                "- `expected_project` is a repository identity guard, usually the repository directory name, not an arbitrary Nilo DB project id.",
                "- `repository_mismatch` returns `ok: false` and no normal status payload.",
                "- MCP multi-workspace: when working across repositories, pass `project_root` or `workspace` to the MCP tool.",
                "- MCP multi-workspace priority: project_root, workspace, then MCP server default cwd.",
                "- Check MCP response identity and use only results whose repository / db_path match the target repository.",
                "- If the default repository differs from the target and the target root is known, retry with `project_root` instead of asking the human.",
                "- On unresolved mismatch, use CLI fallback without asking the human: run `nilo status --ai` and then `nilo next` from the target repository cwd.",
                "- Do not ask humans for missing values that Nilo output or project state can safely infer uniquely.",
                "- For release recipe `target_version`, use the next patch when the current version and latest git tag match, or when no SemVer tag exists and the current version is unique.",
                "- Ask only for multiple candidates, contradictory state, or pre-publication/destructive-operation confirmation.",
                "",
                "Work size:",
                "- Before implementation, judge whether the request is small or large.",
                "- Small work can proceed as a normal task.",
                "- A coherent bug fix can proceed as a normal task even when it touches several files.",
                "- For large work, recommend roadmap planning to the human instead of creating it automatically.",
                "",
                "Use roadmap first when the work:",
                "- has multiple features or implementation tracks,",
                "- has unclear scope or several independent completion criteria,",
                "- changes DB schema or migrations with broad data or compatibility impact,",
                "- adds or changes CLI commands together with broader workflow behavior,",
                "- changes status / next / AI-facing output together with broader workflow behavior,",
                "- requires README/docs/tests together across a broad change,",
                "- affects compatibility or safety-sensitive flows with broad impact.",
                "",
                "Roadmap flow:",
                "- Wait for human approval before creating a roadmap.",
                "- `nilo roadmap discuss` to generate discussion context without changing state.",
                "- Draft a RoadmapProposal from that context.",
                "- Import it with `nilo roadmap import` or accept immediately with `nilo roadmap adopt`.",
                "- human accepts pending revisions with `nilo roadmap accept`",
                "- `nilo roadmap task-plan`",
                "- then proceed task by task.",
                "",
                "Useful commands:",
                "- nilo status --ai",
                "- nilo status --ai --json",
                "- nilo task show --task <task_id> --ai",
                "- nilo review show --task <task_id> --ai",
                "- nilo evidence show --task <task_id> --ai",
                "- nilo doctor ai-context",
            ]
        )
    )


def cmd_migrate(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        files = legacy_agent_block_files()
        if not files:
            print("tracked agent instructions: no deprecated Nilo managed blocks found")
        else:
            print("tracked agent instructions: deprecated Nilo managed blocks found")
            for path in files:
                print(f"- {path.name}")
        if not args.apply:
            if files:
                print("Run `nilo migrate --apply` to remove these blocks and refresh local runtime files.")
            return

        project = project_for_current_directory(store)
        install_agent_blocks(project, list(AGENT_TARGET_FILES))
        for path in files:
            current = path.read_text(encoding="utf-8")
            path.write_text(remove_nilo_managed_block(current), encoding="utf-8")
            print(f"updated: {path.name}")
    finally:
        store.close()


def cmd_upgrade(args: argparse.Namespace) -> None:
    code = run_upgrade(dry_run=args.dry_run, db_path=args.db)
    if code != 0:
        raise SystemExit(code)


def cmd_update_check(args: argparse.Namespace) -> None:
    if is_disabled():
        print("Nilo update check skipped: disabled by NILO_NO_UPDATE_CHECK.")
        return
    print(update_message(check_for_update(), language="en"))


def cmd_init(args: argparse.Namespace) -> None:
    project_id = Path.cwd().name
    boundary = resolve_project_boundary(create_missing=True, repair=bool(getattr(args, "repair_project_binding", False)))
    store = Store(args.db)
    try:
        project = store.get("projects", project_id)
        if project:
            print(f"project exists: {project_id}")
        else:
            project = default_project_row(project_id, now_iso())
            store.insert("projects", project)
            print(f"created project: {project_id}")
        print(f"project binding: {boundary.binding_path}")
        install_agent_blocks(project, list(AGENT_TARGET_FILES))
        print_legacy_agent_block_guidance(legacy_agent_block_files())
    finally:
        store.close()


def cmd_instruct(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        project = store.get("projects", task["project_id"])
        if not project:
            raise SystemExit(f"project not found: {task['project_id']}")
        if requires_understanding_gate(task) and not understanding_approved(store, task["id"]):
            raise SystemExit("understanding check approval required before instruction generation")

        store.update("tasks", task["id"], {"base_commit": head_commit(Path.cwd())})
        task = store.get("tasks", task["id"])

        boundary = resolve_project_boundary(db_path=args.db)
        body, report_format = build_instruction(project, task)
        body = f"{project_boundary_prompt(boundary)}\n\n{body}"
        created_at = now_iso()
        instruction = {
            "id": make_id("instruction"),
            "task_id": task["id"],
            "applied_rule_ids": [],
            "degradation_mode": task["degradation_mode"],
            "body_md": body,
            "report_format_md": report_format,
            "created_at": created_at,
        }
        store.insert("instructions", instruction)
        print(body)
    finally:
        store.close()


def cmd_report_import(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        if args.file:
            markdown = read_text_or_exit(Path(args.file))
        else:
            markdown = sys.stdin.read()
        if not markdown.strip():
            raise SystemExit("report body is empty")

        boundary = resolve_project_boundary(db_path=args.db)
        try:
            require_write_fence(boundary)
        except ProjectBoundaryError as exc:
            record_nilo_issue_for_task(store, task["project_id"], task["id"], "report import", exc, boundary)
            raise SystemExit(str(exc)) from exc
        try:
            result = import_agent_report(store, task, markdown, args.agent, Path.cwd(), evaluate_evidence)
        except TransitionError as exc:
            raise SystemExit(f"{exc.message}{(': ' + exc.remediation) if exc.remediation else ''}") from exc
        check = {"status": result.audit_notes[0] if result.audit_notes else "unknown", "issues": result.warnings}

        print(f"report_form_status: {check['status']}")
        if check["issues"]:
            print("issues:")
            for issue in check["issues"]:
                print(f"- {issue}")
    finally:
        store.close()


def cmd_understanding_prepare(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        body = build_understanding_prompt(task)
        row = {
            "id": make_id("understanding"),
            "task_id": args.task,
            "status": "understanding_required",
            "body_md": body,
            "created_at": now_iso(),
        }
        store.insert("understanding_checks", row)
        print(body)
    finally:
        store.close()


def cmd_understanding_import(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        if args.file:
            body = read_text_or_exit(Path(args.file))
        else:
            body = sys.stdin.read()
        if not body.strip():
            raise SystemExit("understanding body is empty")
        row = {
            "id": make_id("understanding"),
            "task_id": args.task,
            "status": "understanding_reported",
            "body_md": body,
            "created_at": now_iso(),
        }
        store.insert("understanding_checks", row)
        print(f"status: understanding_reported")
        print(f"understanding_check: {row['id']}")
    finally:
        store.close()


def cmd_understanding_approve(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        try:
            result = approve_understanding(
                store,
                args.task,
                actor=args.actor,
                reason=args.reason,
                human_confirm=args.human_confirm,
                decision_source="human_interactive",
                decision_note=args.decision_note,
            )
        except TransitionError as exc:
            raise SystemExit(f"{exc.message}{(': ' + exc.remediation) if exc.remediation else ''}") from exc
        print("status: approved_to_implement")
        print(f"understanding_check: {result.created_ids['understanding_check']}")
    finally:
        store.close()


def cmd_outcome_record(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        concerns = args.concern or []
        decision = args.decision
        if decision in ("accepted", "accepted_with_concerns"):
            boundary = resolve_project_boundary(db_path=args.db)
            try:
                require_write_fence(boundary)
            except ProjectBoundaryError as exc:
                record_nilo_issue_for_task(store, task["project_id"], task["id"], f"outcome {decision}", exc, boundary)
                raise SystemExit(str(exc)) from exc
        try:
            result = record_outcome_decision(
                store,
                args.task,
                decision=decision,
                actor="human",
                reason=args.reason,
                concerns=concerns,
                human_confirm=getattr(args, "human_confirm", False),
                decision_source="human_interactive",
                decision_note=getattr(args, "decision_note", ""),
                cwd=Path.cwd(),
            )
        except TransitionError as exc:
            raise SystemExit(f"{exc.message}{(': ' + exc.remediation) if exc.remediation else ''}") from exc
        print(f"status: {outcome_status(decision)}")
        if "task_completion" in result.created_ids:
            print(f"task_completion: {result.created_ids['task_completion']}")
    finally:
        store.close()


def cmd_verification_run(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        result = run_local_verification(args.command, Path.cwd(), args.timeout)
        result.setdefault("metadata", {})["verification_mode"] = args.mode
        boundary = resolve_project_boundary(db_path=args.db)
        try:
            require_write_fence(boundary)
        except ProjectBoundaryError as exc:
            record_nilo_issue_for_task(store, task["project_id"], task["id"], args.command, exc, boundary)
            raise SystemExit(str(exc)) from exc
        row = {
            "id": make_id("verification"),
            "task_id": args.task,
            "evidence_check_id": None,
            **result,
        }
        try:
            record_verification_run(store, args.task, row=row, actor="nilo")
        except TransitionError as exc:
            raise SystemExit(f"{exc.message}{(': ' + exc.remediation) if exc.remediation else ''}") from exc
        for issue in result["metadata"]["secret_issues"]:
            record_failure_log(
                store,
                task["project_id"],
                task["id"],
                "",
                "secret_detected",
                issue,
                "high",
                source="verification_run",
                actor="nilo",
                related_id=row["id"],
                snapshot=compact_snapshot(current_git_snapshot(Path.cwd())),
                status="open",
            )
        print(f"verification_run: {row['id']}")
        print(f"mode: {args.mode}")
        print(f"exit_code: {row['exit_code']}")
        print(f"timed_out: {bool(row['timed_out'])}")
    finally:
        store.close()
