from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ..cli import (
    AGENT_TARGET_FILES,
    LEGACY_AGENT_TARGET_FILES,
    NILO_BLOCK_BEGIN,
    NILO_BLOCK_END,
    NILO_GENERATED_MARKER,
    NILO_RUNTIME_INSTRUCTION_PATH,
    build_agent_instruction_block,
    requires_understanding_gate,
    understanding_approved,
)
from ..agent_report_import import import_agent_report
from ..cli_support import make_id, read_text_or_exit
from ..gitmeta import git_output, head_commit
from ..guard import evaluate_evidence
from ..instruction import build_instruction, build_understanding_prompt
from ..project_model import default_project_row
from ..snapshot import compact_snapshot, current_git_snapshot
from ..store import Store
from ..task_logic import outcome_status
from ..timeutil import now_iso
from ..upgrade import run_upgrade
from ..verification import run_local_verification


def cmd_agent_install(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        project = store.get("projects", args.project)
        if not project:
            raise SystemExit(f"project not found: {args.project}")
        targets = list(AGENT_TARGET_FILES) if args.target == "all" else [args.target]
        install_agent_blocks(project, targets)
    finally:
        store.close()


def install_agent_blocks(project: dict, targets: list[str], *, warn_unmanaged: bool = True) -> None:
    runtime_body = build_agent_instruction_block(project, "all")
    write_runtime_instruction_body(runtime_body)
    for target in targets:
        if target == "claude-code":
            write_claude_local_bridge(warn_unmanaged=warn_unmanaged)
        elif target == "codex":
            write_codex_override(runtime_body, warn_unmanaged=warn_unmanaged)
    ensure_nilo_git_exclude_entries()


def generated_file_header() -> str:
    return f"{NILO_GENERATED_MARKER}\n\n"


def write_generated_file(path: Path, content: str, *, force: bool = False, warn_unmanaged: bool = True) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if NILO_GENERATED_MARKER not in current and not force:
            if warn_unmanaged:
                print(f"warning: not overwriting unmanaged local file: {path.name}")
            return False
        if current == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"updated: {display_path(path)}")
    return True


def display_path(path: Path) -> str:
    try:
        return path.relative_to(Path.cwd()).as_posix()
    except ValueError:
        return path.as_posix()


def write_runtime_instruction_body(runtime_body: str, *, force: bool = True) -> bool:
    path = Path.cwd() / NILO_RUNTIME_INSTRUCTION_PATH
    return write_generated_file(path, generated_file_header() + runtime_body, force=force)


def write_claude_local_bridge(*, force: bool = False, warn_unmanaged: bool = True) -> bool:
    body = (
        generated_file_header()
        + "# Nilo runtime instructions\n\n"
        + "This file is generated by Nilo and is intentionally local to this working tree.\n"
        + "Do not edit it manually.\n\n"
        + "Read the following Nilo-generated runtime instructions before starting work:\n\n"
        + f"@{NILO_RUNTIME_INSTRUCTION_PATH}\n"
    )
    return write_generated_file(Path.cwd() / AGENT_TARGET_FILES["claude-code"], body, force=force, warn_unmanaged=warn_unmanaged)


def write_codex_override(runtime_body: str, *, force: bool = False, warn_unmanaged: bool = True) -> bool:
    body = (
        generated_file_header()
        + "# Nilo runtime instructions\n\n"
        + "This file is generated by Nilo and is intentionally local to this working tree.\n"
        + "Do not edit it manually.\n\n"
        + runtime_body
    )
    return write_generated_file(Path.cwd() / AGENT_TARGET_FILES["codex"], body, force=force, warn_unmanaged=warn_unmanaged)


def ensure_nilo_git_exclude_entries() -> None:
    path = git_exclude_path(Path.cwd())
    if path is None:
        print("warning: not a git work tree; skipping .git/info/exclude update")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = current.splitlines()
    comment = "# Nilo local runtime files"
    required = [".nilo/", "CLAUDE.local.md", "AGENTS.override.md"]
    comparable = {line.strip() for line in lines}
    missing = [entry for entry in required if entry.strip() not in comparable]
    if not missing:
        return
    if comment not in comparable:
        missing.insert(0, comment)
    prefix = current
    if prefix and not prefix.endswith(("\n", "\r")):
        prefix += "\n"
    path.write_text(prefix + "\n".join(missing) + "\n", encoding="utf-8")
    print("updated: .git/info/exclude")


def git_exclude_path(cwd: Path) -> Path | None:
    code, out, _ = git_output(["rev-parse", "--git-path", "info/exclude"], cwd)
    if code != 0 or not out.strip():
        return None
    path = Path(out.strip())
    if not path.is_absolute():
        path = cwd / path
    return path


def local_instruction_warnings() -> list[str]:
    warnings: list[str] = []
    for filename in AGENT_TARGET_FILES.values():
        path = Path.cwd() / filename
        if path.exists() and NILO_GENERATED_MARKER not in path.read_text(encoding="utf-8"):
            warnings.append(f"unmanaged local instruction file: {filename}")
    for filename in LEGACY_AGENT_TARGET_FILES.values():
        path = Path.cwd() / filename
        if path.exists() and NILO_BLOCK_BEGIN in path.read_text(encoding="utf-8"):
            warnings.append(f"deprecated Nilo managed block remains in tracked agent file: {filename}")
    return warnings


def legacy_agent_block_files() -> list[Path]:
    files: list[Path] = []
    for filename in LEGACY_AGENT_TARGET_FILES.values():
        path = Path.cwd() / filename
        if path.exists() and NILO_BLOCK_BEGIN in path.read_text(encoding="utf-8"):
            files.append(path)
    return files


def print_legacy_agent_block_guidance(files: list[Path]) -> None:
    if not files:
        return
    names = ", ".join(path.name for path in files)
    print(f"warning: deprecated Nilo managed block remains in tracked agent file(s): {names}")
    print("Nilo no longer updates tracked CLAUDE.md / AGENTS.md files by default.")
    print("To remove the old generated block and refresh local runtime files, run:")
    print("  nilo migrate --apply")


def remove_nilo_managed_block(text: str) -> str:
    begin = text.find(NILO_BLOCK_BEGIN)
    end = text.find(NILO_BLOCK_END)
    if begin == -1 and end == -1:
        return text
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit("malformed Nilo managed block")
    end += len(NILO_BLOCK_END)
    before = text[:begin].rstrip()
    after = text[end:].lstrip()
    if before and after:
        return before + "\n\n" + after
    if before:
        return before + "\n"
    return after


def project_for_current_directory(store: Store) -> dict:
    project_id = Path.cwd().name
    project = store.get("projects", project_id)
    return project if project else default_project_row(project_id, now_iso())


def cmd_doctor(args: argparse.Namespace) -> None:
    project_id = Path.cwd().name
    store = Store(args.db)
    try:
        project = store.get("projects", project_id)
        if not project:
            project = default_project_row(project_id, now_iso())
        if args.fix_local_instructions:
            install_agent_blocks(project, list(AGENT_TARGET_FILES), warn_unmanaged=False)
        warnings = local_instruction_warnings()
        runtime_path = Path.cwd() / NILO_RUNTIME_INSTRUCTION_PATH
        claude_path = Path.cwd() / AGENT_TARGET_FILES["claude-code"]
        codex_path = Path.cwd() / AGENT_TARGET_FILES["codex"]
        exclude_path = git_exclude_path(Path.cwd())
        checks = {
            NILO_RUNTIME_INSTRUCTION_PATH: runtime_path.exists(),
            AGENT_TARGET_FILES["claude-code"]: claude_path.exists() and f"@{NILO_RUNTIME_INSTRUCTION_PATH}" in claude_path.read_text(encoding="utf-8"),
            AGENT_TARGET_FILES["codex"]: codex_path.exists() and NILO_BLOCK_BEGIN in codex_path.read_text(encoding="utf-8"),
            ".git/info/exclude": bool(exclude_path and exclude_path.exists() and ".nilo/" in exclude_path.read_text(encoding="utf-8")),
        }
        for name, ok in checks.items():
            print(f"{name}: {'ok' if ok else 'missing'}")
        for warning in warnings:
            print(f"warning: {warning}")
    finally:
        store.close()


def cmd_migrate(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        files = legacy_agent_block_files()
        if not files:
            print("tracked agent instructions: no deprecated Nilo managed blocks found")
        else:
            print("tracked agent instructions: deprecated Nilo managed blocks found")
            for path in files:
                print(f"- {path.name}")
        if not args.apply:
            if files:
                print("Run `nilo migrate --apply` to remove these blocks and refresh local runtime files.")
            return

        project = project_for_current_directory(store)
        install_agent_blocks(project, list(AGENT_TARGET_FILES))
        for path in files:
            current = path.read_text(encoding="utf-8")
            path.write_text(remove_nilo_managed_block(current), encoding="utf-8")
            print(f"updated: {path.name}")
    finally:
        store.close()


def cmd_upgrade(args: argparse.Namespace) -> None:
    code = run_upgrade(dry_run=args.dry_run, db_path=args.db)
    if code != 0:
        raise SystemExit(code)


def cmd_init(args: argparse.Namespace) -> None:
    project_id = Path.cwd().name
    store = Store(args.db)
    try:
        project = store.get("projects", project_id)
        if project:
            print(f"project exists: {project_id}")
        else:
            project = default_project_row(project_id, now_iso())
            store.insert("projects", project)
            print(f"created project: {project_id}")
        install_agent_blocks(project, list(AGENT_TARGET_FILES))
        print_legacy_agent_block_guidance(legacy_agent_block_files())
    finally:
        store.close()


def cmd_instruct(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        project = store.get("projects", task["project_id"])
        if not project:
            raise SystemExit(f"project not found: {task['project_id']}")
        if requires_understanding_gate(task) and not understanding_approved(store, task["id"]):
            raise SystemExit("understanding check approval required before instruction generation")

        store.update("tasks", task["id"], {"base_commit": head_commit(Path.cwd())})
        task = store.get("tasks", task["id"])

        body, report_format = build_instruction(project, task)
        created_at = now_iso()
        instruction = {
            "id": make_id("instruction"),
            "task_id": task["id"],
            "applied_rule_ids": [],
            "degradation_mode": task["degradation_mode"],
            "body_md": body,
            "report_format_md": report_format,
            "created_at": created_at,
        }
        store.insert("instructions", instruction)
        print(body)
    finally:
        store.close()


def record_failure_and_rule(store: Store, project_id: str, task_id: str, report_id: str, category: str, message: str, severity: str) -> None:
    failure = {
        "id": make_id("failure"),
        "project_id": project_id,
        "task_id": task_id,
        "report_id": report_id,
        "category": category,
        "message": message,
        "severity": severity,
        "created_at": now_iso(),
    }
    store.insert("failure_logs", failure)


def cmd_report_import(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        if args.file:
            markdown = read_text_or_exit(Path(args.file))
        else:
            markdown = sys.stdin.read()
        if not markdown.strip():
            raise SystemExit("report body is empty")

        result = import_agent_report(store, task, markdown, args.agent, Path.cwd(), evaluate_evidence)
        check = result["evidence_status"]

        print(f"report_form_status: {check['status']}")
        if check["issues"]:
            print("issues:")
            for issue in check["issues"]:
                print(f"- {issue}")
    finally:
        store.close()


def cmd_understanding_prepare(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        body = build_understanding_prompt(task)
        row = {
            "id": make_id("understanding"),
            "task_id": args.task,
            "status": "understanding_required",
            "body_md": body,
            "created_at": now_iso(),
        }
        store.insert("understanding_checks", row)
        print(body)
    finally:
        store.close()


def cmd_understanding_import(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        if args.file:
            body = read_text_or_exit(Path(args.file))
        else:
            body = sys.stdin.read()
        if not body.strip():
            raise SystemExit("understanding body is empty")
        row = {
            "id": make_id("understanding"),
            "task_id": args.task,
            "status": "understanding_reported",
            "body_md": body,
            "created_at": now_iso(),
        }
        store.insert("understanding_checks", row)
        print(f"status: understanding_reported")
        print(f"understanding_check: {row['id']}")
    finally:
        store.close()


def cmd_understanding_approve(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        latest = store.latest_for_task("understanding_checks", args.task)
        if not latest or latest["status"] != "understanding_reported":
            raise SystemExit("understanding report import required before approval")
        body = latest["body_md"]
        row = {
            "id": make_id("understanding"),
            "task_id": args.task,
            "status": "approved_to_implement",
            "body_md": body,
            "created_at": now_iso(),
        }
        store.insert("understanding_checks", row)
        print("status: approved_to_implement")
        print(f"understanding_check: {row['id']}")
    finally:
        store.close()


def cmd_outcome_record(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        latest_report = store.latest_for_task("agent_reports", args.task)
        latest_verification = store.latest_for_task("verification_runs", args.task)
        latest_review = store.latest_for_task("review_results", args.task)
        concerns = args.concern or []
        decision = args.decision
        snapshot = compact_snapshot(current_git_snapshot(Path.cwd()))
        accepted = decision in ("accepted", "accepted_with_concerns")
        row = {
            "id": make_id("completion" if accepted else "outcome"),
            "task_id": args.task,
            "actor": "human",
            "completed_by": "human",
            "completed_snapshot": snapshot,
            "completion_note": args.reason,
            "accepted_verification_run_ids": [latest_verification["id"]] if accepted and latest_verification else [],
            "accepted_review_result_ids": [latest_review["id"]] if accepted and latest_review else [],
            "human_decision_note": "\n".join([args.reason, *concerns]).strip(),
            "completed_with_reservations": decision == "accepted_with_concerns",
            "reason": args.reason,
            "completed_at": now_iso(),
            "created_at": now_iso(),
        }
        if accepted:
            store.insert("task_completions", row)
        if decision in ("rejected", "rework_required"):
            severity = "high" if decision == "rejected" else "medium"
            record_failure_and_rule(
                store,
                task["project_id"],
                task["id"],
                latest_report["id"] if latest_report else "",
                f"human_{decision}",
                args.reason,
                severity,
            )
        print(f"status: {outcome_status(decision)}")
        if accepted:
            print(f"task_completion: {row['id']}")
    finally:
        store.close()


def cmd_verification_run(args: argparse.Namespace) -> None:
    store = Store(args.db)
    try:
        task = store.get("tasks", args.task)
        if not task:
            raise SystemExit(f"task not found: {args.task}")
        result = run_local_verification(args.command, Path.cwd(), args.timeout)
        row = {
            "id": make_id("verification"),
            "task_id": args.task,
            "evidence_check_id": None,
            **result,
        }
        store.insert("verification_runs", row)
        for issue in result["metadata"]["secret_issues"]:
            record_failure_and_rule(
                store,
                task["project_id"],
                task["id"],
                "",
                "secret_detected",
                issue,
                "high",
            )
        print(f"verification_run: {row['id']}")
        print(f"exit_code: {row['exit_code']}")
        print(f"timed_out: {bool(row['timed_out'])}")
    finally:
        store.close()
